### ISSUE TITLE
Question: About deploy action

### ISSUE THREAD

**Issue by zedtux** [jeromemacias/webistrano#4]
In the stage screen, there are 2 links about deployment:
- Deploy
- Rollback

About **Deploy**, why don't you execute it with migrations?

I know that deployments could not contain migration script, but it could be confusing when deploying without taking care of migration scripts and then having exception in the application because of a missing column for example.
(Today we're using the dropdown to select the right action).

I also know that there are schema less databases, then the migration option is to avoid.
Could we then imagine a checkbox nearby the **Deploy** or an option somewhere to define the action behind the **Deploy** ?

**Comment by jeromemacias** [comment]
Links about deployment in the stage screen can be configured into your `config/webistrano.yml` (`:default_deployment_shortcuts:`) configuration file.

Hope this will help you.

**Comment by zedtux** [comment]
Hohooo nice! :thumbsup:

Let me check this!
