### ISSUE TITLE
Add new host failed with "Name is not a valid hostname or IP"

### ISSUE THREAD

**Issue by zedtux** [jeromemacias/webistrano#5]
Today I'm trying to add a new host (using its hostname) but I have the error message

```
Name is not a valid hostname or IP
```

I've checked the regex that's used:

``` ruby
"" =~ /\A[a-zA-Z0-9\_\-\.]+\Z/
=> nil
>> "myhostname" =~ /\A[a-zA-Z0-9\_\-\.]+\Z/
=> 0
>> ("myhostname" =~ /\A[a-zA-Z0-9\_\-\.]+\Z/) == true
=> false
>> ("" =~ /\A[a-zA-Z0-9\_\-\.]+\Z/) == true
=> false
```

`nil` will return false, but 0 will not be true I think.
Do you have any test on this ?

FYI: Adding a host with its IP address work fine.

**Comment by jeromemacias** [comment]
There are some test on this :

``` ruby
  def test_validation_of_name_if_domain_name
    assert valid_host_name('map.example.com')
    assert valid_host_name('web12.example.com')
    assert valid_host_name('localhost')

    # some invalid domains
    assert invalid_host_name('mail:example.com')
    assert invalid_host_name('mail*.#.example.com')
  end
```

I will check if it's work for me.

**Comment by zedtux** [comment]
The host I tried is something like **machinename01.subdomain.domain.ltd**

Don't know if it can help.

**Comment by jeromemacias** [comment]
It's work for me, on mysql.

I will add an unit test with your example.

**Comment by zedtux** [comment]
Alright. Then I will check on my side (I'm using PostgreSQL).
